// src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Injectable } from '@angular/core';
import axios from 'axios';
import { Router } from '@angular/router';
@Injectable({ providedIn: 'root' })
@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent implements OnInit {
  datatype: any;
  user: any;
  id_category=0;
id : any
  constructor(private router : Router) {}

  changeKey(){
    this.id =JSON.stringify(this.id_category)
    localStorage.setItem('key',this.id)
    // location.reload();
    this.router.navigate(["/profile-user"])

  }
  
  logout(){
    this.id_category = 0
    this.id =JSON.stringify(this.id_category)
    localStorage.removeItem("user")
    localStorage.setItem('key',this.id)
    localStorage.removeItem('profil')
    // location.reload();
  }
  

  ngOnInit(): void {
    axios.get("http://localhost:3001/api/items/type").then((response) => {
      this.datatype = response.data;
      console.log(this.datatype);
    });
    this.user=JSON.parse(localStorage.getItem('user')!)
    console.log(this.user)
    if(this.user!==null){
      this.id_category=this.user.id_category
    }
  }
  
}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-lg p-3 mb-5">
  <a
    class="title-nav nav-item nav-link"
    routerLink="/"
    routerLinkActive="active"
    >Space<svg
      xmlns="http://www.w3.org/2000/svg"
      height="24px"
      viewBox="0 0 24 24"
      width="24px"
      fill="white"
    >
      <path d="M0 0h24v24H0V0z" fill="none" />
      <path
        d="M12 3L1 9l4 2.18v6L12 21l7-3.82v-6l2-1.09V17h2V9L12 3zm6.82 6L12 12.72 5.18 9 12 5.28 18.82 9zM17 15.99l-5 2.73-5-2.73v-3.72L12 15l5-2.73v3.72z"
      /></svg
    >Ed</a
  >
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNavAltMarkup"
    aria-controls="navbarNavAltMarkup"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a
        class="nav-item nav-link active"
        routerLink="/lectures"
        *ngIf="id_category !== 0 && id_category !== 3"
        href="#"
        >Lectures</a
      >
      <a
        class="nav-item nav-link active"
        routerLink="/booking"
        *ngIf="id_category !== 0 && id_category !== 1"
        href="#"
        >Booking</a
      >
      <!-- <a class="nav-item nav-link active" routerLink="/search" href="#">Search</a> -->
      <a
        class="login-btn nav-item nav-link active"
        routerLink="/login"
        *ngIf="id_category === 0"
        >Log-in</a
      >
      <!-- <a class="signup-btn nav-item nav-link active" *ngIf='id_category===0' routerLink="/signup" >Signup</a> -->
      <a
        class="signup-btn nav-item nav-link active"
        routerLink="/profile-user"
        *ngIf="id_category !== 0"
        (click)="changeKey()"
        >Profile</a
      >
      <a
        class="signup-btn nav-item nav-link active"
        routerLink="/post-lecture"
        *ngIf="id_category !== 0 && id_category !== 3"
        >Post New Lecture</a
      >
      <a
        class="nav-item nav-link active"
        routerLink="/add-teacher"
        *ngIf="id_category === 1"
        href="#"
        >Add teacher</a
      >
      <a
        class="nav-item nav-link active"
        routerLink="/add-type"
        *ngIf="id_category === 1"
        href="#"
        >Add type</a
      >
      <a class="signup-btn nav-item nav-link active" routerLink="/about-us"
        >About us</a
      >
      <a
        class="signup-btn nav-item nav-link active"
        (click)="logout()"
        routerLink="/login"
        *ngIf="id_category !== 0"
        >Log-Out</a
      >
    </div>
  </div>
</nav>

// src/app/navbar/NavBar.vue
<script>
import axios from "axios";

export default {
  props:["change"],
  data() {
    return {
      datatype: [],
      key:0,
      user:{},
      id_category:0
      
    };
  },
  mounted() {
    axios.get("http://localhost:3001/api/items/type").then((response) => {
      this.datatype = response.data;
      console.log(this.datatype);
    });
    this.user=JSON.parse(localStorage.getItem('user'))
    console.log(this.user)
    if(this.user!==null){
      this.id_category=this.user.id_category
      this.index=1
    }
  },
  methods: {
    changeKey(){
      localStorage.setItem('key',this.key)
      location.reload();
    },
    logout(){
      localStorage.removeItem("user")
      localStorage.setItem('key',this.key)
      localStorage.removeItem('profil')
      location.reload();
    }
  }
};
</script>
<template>
  <div>
    <ul>
      <div className="centerReste">
        <li>
          <router-link to="/"> <img src="https://media.discordapp.net/attachments/940527646540972052/941874057379455006/spaceeducationblanc.png?width=1313&height=671" alt="" class="img"> </router-link>
        </li>
        <li>
          <a> <router-link to="/"> Home </router-link> </a>
        </li>
        <li>
          <a> <router-link to="/AboutUs"> AboutUs </router-link> </a>
        </li>
        <li>
          <a> <router-link to="/Booked" v-if="this.id_category!==0" > Booked </router-link> </a>
        </li>
        <li>
          <a> <router-link to="/Lectures" v-if="this.id_category!==0&&this.id_category !==3 " > Lectures </router-link> </a>
        </li>
        <li>
          <a> <router-link v-if="this.id_category!==0&&this.id_category !==3 "  to="/Post" > Post </router-link> </a>
        </li>
        
        <!-- <li>
          <a> <router-link to="/Payment"> Payment </router-link> </a>
        </li> -->
        <li>
          <a> <router-link v-if="this.id_category===1" to="/ListUser"> List User </router-link> </a>
        </li>
        <li>
          <a> <router-link v-if="this.id_category===1" to="/AddType"> Add Type </router-link> </a>
        </li>
      </div>
      <div className="center">
        <li>
          <a> <router-link v-if="this.id_category===0" to="/Login"> Login </router-link> </a>
        </li>
        <li>
          <a> <router-link v-if="this.id_category===0" to="/Signup"> Signup </router-link> </a>
        </li>
        <li>
          <a @click="changeKey"> <router-link v-if="this.id_category!==0" to="/Profil"> Profil </router-link> </a>
        </li>
        <li>
          <a @click="logout"> <router-link v-if="this.id_category!==0" to="/"> Logout </router-link> </a>
        </li>
      </div>
    </ul>
  </div>
  


</template>

<style>

</style>
