// src/app/lectures/lectures.component.ts
import { Component, OnInit } from '@angular/core';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import axios from 'axios';


@Injectable({
  providedIn: 'root'
})


@Component({
  selector: 'app-lectures',
  templateUrl: './lectures.component.html',
  styleUrls: ['./lectures.component.css']
})

export class LecturesComponent implements OnInit {
  posts:any;
userInfo :any
dataCategory : any
id_user:any
id_category:any
  constructor(private http: HttpClient) { }
  async getLectures(){
    this.http.get('http://localhost:3001/api/items/homePosts').subscribe((result)=>{
      this.posts = result
      
       this.userInfo= JSON.parse(localStorage.getItem("user")!)
      
      console.log(this.posts,"HELOO")
    })
  

    await axios.get(`http://localhost:3001/api/items/profilPosts/${this.userInfo.id_user}`).then((response) => {
      this.posts = response.data;
      console.log(this.posts);
      // localStorage.setItem("type", JSON.stringify(this.type));
    });
    await axios.get("http://localhost:3001/api/items/category").then((res) => {
      this.dataCategory = res.data;
      console.log(this.dataCategory);
    });
  }
  change(event:any) {
    this.id_user= event.target.value;
    this.id_category = event.target.value
  }


  async add() {
    var option = {
      id_category: this.id_category,
      // id_user: this.id_user,
    };
    console.log(option);
    await axios
      .put(`http://localhost:3001/api/items/user/${this.id_user}`, option)
      .then((response) => {
        location.reload();
        console.log(response);
        
      })
      .catch((error) => {
        console.log(error);
      });
  }

  ngOnInit(): void{
    // axios
    // .get('http://localhost:3001/api/items/homePosts')
    // .then(result=>{
    //   console.log(result)
    //   this.posts = result
    // })
  }
}

<div class="formbg">
    <div class="formbg-inner padding-horizontal--48">
      <span class="padding-bottom--15">Users List </span>
      <!-- <form id="stripe-login"> -->
      <div class="field padding-bottom--24">
        <table>
          <td><h5>title</h5></td>
          <td><h5>category</h5></td>
          <!-- <td><h5>description</h5></td> -->
          <td><h5>Picture</h5></td>
          
          <td><h5>Create room</h5></td>
          <tr *ngFor="let elem of posts" :key="elem">
            <td>{{ elem.title }}</td>
            <td>{{ elem.label_type }} <img class="img" :src="elem.image_type" alt="" /></td>
            <!-- <td>{{ elem.description }}</td> -->
            <td><img class="img" :src="elem.image_post" alt="" /></td>
            
            <td><a href="http://localhost:8080/">Create</a></td>
          </tr>
        </table>
        <!-- <hr />
        <h4>change category of User</h4>
        <div class="flex-flex">
          <label>Users</label>
          <select name="id_user" @input="change">
            <option value="">select User</option>

            <option
              v-for="elem in this.users"
              :key="elem"
              :value="elem.id_user"
            >
              {{ elem.firstName }} {{ elem.firstName }}
            </option>
          </select>
          <label>select User</label>
          <select name="id_category" @input="change">
            <option value="">select Category</option>

            <option
              v-for="elem in this.dataCategory"
              :key="elem"
              :value="elem.id_category"
            >
              {{ elem.label_category }}
            </option>
          </select>
          <button v-on:click="add()">Submit</button>
        </div> -->

        
      </div>
    </div>
  </div>

// src/app/lectures/Lectures.vue

<script>
import axios from "axios";
export default {
  components: {},
  data() {
    return {
      id_user: null,
      id_category: null,
      users: [],
      dataCategory: [],
      user: JSON.parse(localStorage.getItem("user")),
      posts:[],
      
      // url: 'http://localhost:3001/api/items/getdata'
    };
  },
  mounted() {
    axios.get(`http://localhost:3001/api/items/profilPosts/${this.user.id_user}`).then((response) => {
      this.posts = response.data;
      console.log(this.posts);
      // localStorage.setItem("type", JSON.stringify(this.type));
    });
    axios.get("http://localhost:3001/api/items/category").then((res) => {
      this.dataCategory = res.data;
      console.log(this.dataCategory);
    });
  },
  methods: {
    change(event) {
      this[event.target.name] = event.target.value;
      console.log(this[event.target.name]);
    },
    add() {
      var option = {
        id_category: this.id_category,
        // id_user: this.id_user,
      };
      console.log(option);
      axios
        .put(`http://localhost:3001/api/items/user/${this.id_user}`, option)
        .then((response) => {
          location.reload();
          console.log(response);
          
        })
        .catch((error) => {
          console.log(error);
        });
    },
  },
};
</script>


<template>
  
</template>

<style>

</style>
