// src/add-teacher/AddTeacher.vue

<script>
import axios from "axios";
export default {
  components: {},
  data() {
    return {
      id_user: null,
      id_category: null,
      users: [],
      dataCategory: [],
      user: JSON.parse(localStorage.getItem("user")),
      
      // url: 'http://localhost:3001/api/items/getdata'
    };
  },
  mounted() {
    axios.get("http://localhost:3001/api/items/userall").then((response) => {
      this.users = response.data;
      console.log(this.users);
      // localStorage.setItem("type", JSON.stringify(this.type));
    });
    axios.get("http://localhost:3001/api/items/category").then((res) => {
      this.dataCategory = res.data;
      console.log(this.dataCategory);
    });
  },
  methods: {
    change(event) {
      this[event.target.name] = event.target.value;
      console.log(this[event.target.name]);
    },
    add() {
      var option = {
        id_category: this.id_category,
        // id_user: this.id_user,
      };
      console.log(option);
      axios
        .put(`http://localhost:3001/api/items/user/${this.id_user}`, option)
        .then((response) => {
          location.reload();
          console.log(response);
          
        })
        .catch((error) => {
          console.log(error);
        });
    },
  },
};
</script>


<template>
 
</template>

<style>

</style>

// src/app/add-teacher/add-teacher.component.ts
import { Component, OnInit } from '@angular/core';
import axios from 'axios';
import { Injectable } from '@angular/core';
@Injectable({ providedIn: 'root' })
@Component({
  selector: 'app-add-teacher',
  templateUrl: './add-teacher.component.html',
  styleUrls: ['./add-teacher.component.css']
})
export class AddTeacherComponent implements OnInit {
users : any
dataCategory : any
id_category : any
id_user: any
user: any
  constructor() { }
  add() {
    if(this.id_category==="Admin"){
      this.id_category = 1
    }if(this.id_category==="Teacher"){
      this.id_category = 2
    }if(this.id_category==="Student"){
      this.id_category = 3
    }
    console.log(this.id_category,"ahhaha")
    var option = {
      id_category: this.id_category,
      id_user: this.id_user,
    };
    console.log(option);
    console.log(this.id_user)
    axios
      .put(`http://localhost:3001/api/items/user/`+this.id_user, option)
      .then((response) => {
        location.reload();
        console.log(response);
      })
      .catch((error) => {
        console.log(error);
      });
  }
  ngOnInit(): void {
    this.user= JSON.parse(localStorage.getItem("user")!)
    axios.get("http://localhost:3001/api/items/userall").then((response) => {
      this.users = response.data;
      console.log(this.users);
      // localStorage.setItem("type", JSON.stringify(this.type));
    });
    axios.get("http://localhost:3001/api/items/category").then((res) => {
      this.dataCategory = res.data;
      console.log(this.dataCategory);
    });
  }
}
<div class="formbg">
  <div class="formbg-inner padding-horizontal--48">
    <span class="padding-bottom--15">Users List </span>
    <hr>
    <!-- <form id="stripe-login"> -->
    <div class="field padding-bottom--24">
      <table>
        <td><h5>First Name</h5></td>
        
        <td><h5>Last Name</h5></td>
        <td><h5>Email</h5></td>
        <td><h5>Category</h5></td>
        <td><h5>Phone Number</h5></td>
        <hr>
        <tr *ngFor="let elem of users" key="elem">
          <td>{{ elem.firstName }}</td>
          <td>{{ elem.lastName }}</td>
          <td>{{ elem.email }}</td>
          <td>{{ elem.label_category }}</td>
          <td>{{ elem.phone }}</td>
        </tr>
        
      </table>
     <hr>
      <h4>change category of User</h4>
      <div class="flex-flex">
        <label>Users</label>
        <select name="id_user" [(ngModel)]="id_user" class="form-select form-select-lg mb-3">
          <option value="">select User</option>
          <option
            *ngFor="let elem of users"
            :key="elem"
            name="id_user"
          >
            {{ elem.firstName }}
          </option>
        </select>
        <label>select User</label>
        <select name="id_category" [(ngModel)]="id_category" class="form-select form-select-lg mb-3">
          <option value="">select Category</option>
          <option
            *ngFor="let elem of dataCategory"
            key="elem"
          >
            {{ elem.label_category }}
          </option>
        </select>
        <button (click)="add()">Submit</button>
      </div>
    </div>
  </div>
</div>
