// src/app/booking/booking.component.ts
import { Component, OnInit } from '@angular/core';
import axios from 'axios';


@Component({
  selector: 'app-booking',
  templateUrl: './booking.component.html',
  styleUrls: ['./booking.component.css']
})
export class BookingComponent implements OnInit {
  booked: any;
  dataCategory: any;
  users: any
  id_user: string ='';
  id_category: string= '';
  user:any //it must be changed to the line commented bellow
  // user: JSON.parse(localStorage.getItem("user")),

  constructor() { }

  async change(event: any){
    [event.target.name] = event.target.value
    console.log(event.target.name);
  }

  add() {
    var option = {
      id_category: this.id_category,
    };
    console.log(option);
    axios
      .put(`http://localhost:3001/api/items/user/${this.id_user}`, option)
      .then((response) => {
        location.reload();
        console.log(response);
        
      })
      .catch((error) => {
        console.log(error);
      });
  }

  ngOnInit(): void {
    axios.get(`http://localhost:3001/api/items/booking/${this.user.id_user}`).then((response) => {
      this.booked = response.data;
      console.log(this.booked);
      // localStorage.setItem("type", JSON.stringify(this.type));
    });
    axios.get("http://localhost:3001/api/items/category").then((res) => {
      this.dataCategory = res.data;
      console.log(this.dataCategory);
    });
  }
}
<div class="formbg">
    <div class="formbg-inner padding-horizontal--48">
      <span class="padding-bottom--15">Users List </span>
      <!-- <form id="stripe-login"> -->
      <div class="field padding-bottom--24">
        <table>
          <td><h5>title</h5></td>
          <td><h5>Teacher</h5></td>
          <td><h5>description</h5></td>
          <td><h5>Picture</h5></td>
          <td><h5>status</h5></td>
          <td><h5>join room</h5></td>
          <tr *ngFor="let elem of booked" :key="elem">
            <td>{{ elem.title }}</td>
            <td>{{ elem.firstName }} {{ elem.lastName }}</td>
            <td>{{ elem.description }}</td>
            <td><img class="img" ng-src="elem.image_post" alt="" /></td>
            <td>{{ elem.status_booking }}</td>
            <td><a href="http://localhost:8080/">join</a></td>
          </tr>
        </table>
        <!-- <hr />
        <h4>change category of User</h4>
        <div class="flex-flex">
          <label>Users</label>
          <select name="id_user" @input="change">
            <option value="">select User</option>

            <option
              v-for="elem in this.users"
              :key="elem"
              :value="elem.id_user"
            >
              {{ elem.firstName }} {{ elem.firstName }}
            </option>
          </select>
          <label>select User</label>
          <select name="id_category" @input="change">
            <option value="">select Category</option>

            <option
              v-for="elem in this.dataCategory"
              :key="elem"
              :value="elem.id_category"
            >
              {{ elem.label_category }}
            </option>
          </select>
          <button v-on:click="add()">Submit</button>
        </div> -->

        
      </div>
    </div>
  </div>

// src/app/booking/Booking.vue

<script>
import axios from "axios";
export default {
  components: {},
  data() {
    return {
      id_user: null,
      id_category: null,
      users: [],
      dataCategory: [],
      user: JSON.parse(localStorage.getItem("user")),
      booked:[],
      
      // url: 'http://localhost:3001/api/items/getdata'
    };
  },
  mounted() {
    axios.get(`http://localhost:3001/api/items/booking/${this.user.id_user}`).then((response) => {
      this.booked = response.data;
      console.log(this.booked);
      // localStorage.setItem("type", JSON.stringify(this.type));
    });
    axios.get("http://localhost:3001/api/items/category").then((res) => {
      this.dataCategory = res.data;
      console.log(this.dataCategory);
    });
  },
  methods: {
    change(event) {
      this[event.target.name] = event.target.value;
      console.log(this[event.target.name]);
    },
    add() {
      var option = {
        id_category: this.id_category,
        // id_user: this.id_user,
      };
      console.log(option);
      axios
        .put(`http://localhost:3001/api/items/user/${this.id_user}`, option)
        .then((response) => {
          location.reload();
          console.log(response);
          
        })
        .catch((error) => {
          console.log(error);
        });
    },
  },
};
</script>


<template>
  
</template>

<style>

</style>
