// src/app/add-type/add-type.component.ts
import { Component, OnInit } from '@angular/core';
import axios from 'axios';
import { Injectable } from '@angular/core';
@Injectable({ providedIn: 'root' })
@Component({
  selector: 'app-add-type',
  templateUrl: './add-type.component.html',
  styleUrls: ['./add-type.component.css'],
})
export class AddTypeComponent implements OnInit {
  title: any;
  description: any;
  datatype: any;
  user: any;
  id_type: any;
  label_type: any;
  image_type: any;
  constructor() {}
  add() {
    var option = {
      label_type: this.label_type,
      image_type: this.image_type,
    };
    console.log(option);
    axios
      .post('http://localhost:3001/api/items/type', option)
      .then((response) => {
        console.log(response);
        location.reload();
      })
      .catch((error) => {
        console.log(error);
      });
  }
  ngOnInit(): void {
    axios.get('http://localhost:3001/api/items/type').then((response) => {
      this.datatype = response.data;
      console.log(this.datatype);
      // localStorage.setItem("type", JSON.stringify(this.type));
    });
    this.user = JSON.parse(localStorage.getItem('user')!);
  }
}

<div class="formbg">
    <div class="formbg-inner padding-horizontal--48">
      <span class="padding-bottom--15">Add New Gategory of lecture</span>
      <!-- <form id="stripe-login"> -->
      <div class="field padding-bottom--24">
        <table>
          <td><h5>ID category of lecture</h5></td>
          <td><h5>Label category of lecture</h5></td>
          <td><h5>image category of lecture</h5></td>

          <tr *ngFor="let elem of datatype" :key="elem">
            <td>{{ elem.id_type }}</td>
            <td>{{ elem.label_type }}</td>
            <td><img class="img" :src="elem.image_type" alt="" /></td>
          </tr>
        </table>
        <hr />
        <div>
          <label>category label of lecture </label>
          <input name="label_type" (change)="change()" />

          <label>image of lecture category</label>
          <input name="image_type" (change)="change()" />

          <button (click)="add()">Submit</button>
        </div>
      </div>
    </div>
  </div>

// src/app/add-type/AddType.vue

<script>
import axios from "axios";
export default {
  components: {},
  data() {
    return {
      title: "",
      description: "",
      datatype: [],
      user: JSON.parse(localStorage.getItem("user")),
      id_type: null,
      // url: 'http://localhost:3001/api/items/getdata'
    };
  },
  mounted() {
    axios.get("http://localhost:3001/api/items/type").then((response) => {
      this.datatype = response.data;
      console.log(this.datatype);
      // localStorage.setItem("type", JSON.stringify(this.type));
    });
  },
  methods: {
    change(event) {
      this[event.target.name] = event.target.value;
      console.log(this[event.target.name]);
    },
    add() {
      var option = {
        label_type: this.label_type,
        image_type: this.image_type,
      };
      console.log(option);
      axios
        .post("http://localhost:3001/api/items/type", option)
        .then((response) => {
          console.log(response);
          location.reload();
        })
        .catch((error) => {
          console.log(error);
        });
    },
  },
};
</script>


<template>
  
</template>

<style>

</style>
